### PR TITLE
implement new service stop command

### PR DESCRIPTION
**Pull request by ilgooz**
under temporary service:newstop name.

depends on https://github.com/mesg-foundation/cli/pull/45.

### CODE REVIEW

**Comment by antho1404** [comment]
Can you fix the conflicts and make sure the checks are green

**Comment by ilgooz** [comment]
waiting on grpc apis to finalise before adding any more commits to this pr

**Comment by ilgooz** [comment]
waiting on grpc apis to finalise before adding any more commits to this pr

**Comment by antho1404** [comment]
closing in favor of https://github.com/mesg-foundation/cli/pull/81

**Pull request closed without merging**
